/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author Windows 10 Pro
 */
import Arbol.Estado;
import Arbol.Jugada;
import java.awt.CardLayout;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import Juego.*;
import javax.swing.Timer;
import Interfaces.*;
import Configuracion.Sistema;
import SistemaDeProduccion.SistemaProduccion;
import javax.swing.JLabel;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    CardLayout cardLayBase;
    CardLayout cardLayOpciones;

    int numeroJugadores, t, a, b, xt, yt, veri = 3, fase = 0, t_h, t_m, dificultad;
    //Para la máquina
    int[] xm1 = {20, 90, 160, 230, 310, 380, 450, 520, 590};
    int ind = 0;
    //Para los movimientos
    int x1, y1, x2, y2, fich_Elim = 0;
    public int COORx = 8, COORy = 8;
    Tablero Tab = new Tablero();
    Ficha Fich = new Ficha();
    Ficha fichas = new Ficha();
    Jugada jugada = new Jugada(2, -1, -1, -1, -1);
    FichasEliminadas fichasEliminadas = new FichasEliminadas();
    JLabel MaquinasBlancas[];
    JLabel MaquinasNegras[];
    Mensaje men;
    int conMaquinas = 0;
    javax.swing.JLabel jlbAux;
    javax.swing.JLabel jlbAux1;
    

    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        cardLayBase = (CardLayout) (pBase.getLayout());
        cardLayOpciones = (CardLayout) (pOpciones.getLayout());
        MaquinasBlancas = new JLabel[9];
        MaquinasNegras = new JLabel[9];
        asignarBlancas();
        asignarNegras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pBase = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        imagen = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pOpciones = new javax.swing.JPanel();
        pOpcion1 = new javax.swing.JPanel();
        btnNuevoJuego = new javax.swing.JButton();
        btnVerReglas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pOpcionJugador = new javax.swing.JPanel();
        btnUnJugador = new javax.swing.JButton();
        btnDosJugadores = new javax.swing.JButton();
        btVolverOJ = new javax.swing.JButton();
        pOpcionFichas = new javax.swing.JPanel();
        btBlancas = new javax.swing.JButton();
        btNegras = new javax.swing.JButton();
        btnVolverOF = new javax.swing.JButton();
        lbMensaje = new javax.swing.JLabel();
        pUnJugador = new javax.swing.JPanel();
        btnFacil = new javax.swing.JButton();
        btnNormal = new javax.swing.JButton();
        btnDificil = new javax.swing.JButton();
        btnVolverUJ = new javax.swing.JButton();
        pMolino = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        fn1 = new javax.swing.JLabel();
        fn2 = new javax.swing.JLabel();
        fn3 = new javax.swing.JLabel();
        fn4 = new javax.swing.JLabel();
        fn5 = new javax.swing.JLabel();
        fn6 = new javax.swing.JLabel();
        fn7 = new javax.swing.JLabel();
        fn8 = new javax.swing.JLabel();
        fn9 = new javax.swing.JLabel();
        fv9 = new javax.swing.JLabel();
        fv8 = new javax.swing.JLabel();
        fv7 = new javax.swing.JLabel();
        fv6 = new javax.swing.JLabel();
        fv5 = new javax.swing.JLabel();
        fv4 = new javax.swing.JLabel();
        fv3 = new javax.swing.JLabel();
        fv2 = new javax.swing.JLabel();
        fv1 = new javax.swing.JLabel();
        a17 = new javax.swing.JLabel();
        a11 = new javax.swing.JLabel();
        a22 = new javax.swing.JLabel();
        a24 = new javax.swing.JLabel();
        a26 = new javax.swing.JLabel();
        a42 = new javax.swing.JLabel();
        a33 = new javax.swing.JLabel();
        a35 = new javax.swing.JLabel();
        a14 = new javax.swing.JLabel();
        a43 = new javax.swing.JLabel();
        a71 = new javax.swing.JLabel();
        a62 = new javax.swing.JLabel();
        a53 = new javax.swing.JLabel();
        a54 = new javax.swing.JLabel();
        a55 = new javax.swing.JLabel();
        a45 = new javax.swing.JLabel();
        a46 = new javax.swing.JLabel();
        a47 = new javax.swing.JLabel();
        a66 = new javax.swing.JLabel();
        a64 = new javax.swing.JLabel();
        a34 = new javax.swing.JLabel();
        a77 = new javax.swing.JLabel();
        a41 = new javax.swing.JLabel();
        a74 = new javax.swing.JLabel();
        lbTablero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbJugadorNegras = new javax.swing.JLabel();
        lbJugadorVerde = new javax.swing.JLabel();
        Victoria = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pBase.setBackground(new java.awt.Color(204, 204, 255));
        pBase.setLayout(new java.awt.CardLayout());

        Inicio.setBackground(new java.awt.Color(255, 255, 255));

        imagen.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tableroInicio1.png"))); // NOI18N

        javax.swing.GroupLayout imagenLayout = new javax.swing.GroupLayout(imagen);
        imagen.setLayout(imagenLayout);
        imagenLayout.setHorizontalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
        imagenLayout.setVerticalGroup(
            imagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        pOpciones.setLayout(new java.awt.CardLayout());

        pOpcion1.setBackground(new java.awt.Color(255, 255, 255));

        btnNuevoJuego.setBackground(new java.awt.Color(51, 51, 51));
        btnNuevoJuego.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnNuevoJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoJuego.setText("Nuevo juego");
        btnNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoJuegoActionPerformed(evt);
            }
        });

        btnVerReglas.setBackground(new java.awt.Color(51, 51, 51));
        btnVerReglas.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnVerReglas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerReglas.setText("Ver reglas");
        btnVerReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReglasActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(51, 51, 51));
        btnSalir.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");

        javax.swing.GroupLayout pOpcion1Layout = new javax.swing.GroupLayout(pOpcion1);
        pOpcion1.setLayout(pOpcion1Layout);
        pOpcion1Layout.setHorizontalGroup(
            pOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOpcion1Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(pOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevoJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerReglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        pOpcion1Layout.setVerticalGroup(
            pOpcion1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOpcion1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnNuevoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnVerReglas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pOpciones.add(pOpcion1, "pOpcion1");

        pOpcionJugador.setBackground(new java.awt.Color(255, 255, 255));

        btnUnJugador.setBackground(new java.awt.Color(51, 51, 51));
        btnUnJugador.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnUnJugador.setForeground(new java.awt.Color(255, 255, 255));
        btnUnJugador.setText("1 Jugador");
        btnUnJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnJugadorActionPerformed(evt);
            }
        });

        btnDosJugadores.setBackground(new java.awt.Color(51, 51, 51));
        btnDosJugadores.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnDosJugadores.setForeground(new java.awt.Color(255, 255, 255));
        btnDosJugadores.setText("2 Jugadores");
        btnDosJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDosJugadoresActionPerformed(evt);
            }
        });

        btVolverOJ.setBackground(new java.awt.Color(51, 51, 51));
        btVolverOJ.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btVolverOJ.setForeground(new java.awt.Color(255, 255, 255));
        btVolverOJ.setText("Volver");
        btVolverOJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverOJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pOpcionJugadorLayout = new javax.swing.GroupLayout(pOpcionJugador);
        pOpcionJugador.setLayout(pOpcionJugadorLayout);
        pOpcionJugadorLayout.setHorizontalGroup(
            pOpcionJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOpcionJugadorLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addGroup(pOpcionJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUnJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDosJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btVolverOJ, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        pOpcionJugadorLayout.setVerticalGroup(
            pOpcionJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOpcionJugadorLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnUnJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDosJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btVolverOJ, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pOpciones.add(pOpcionJugador, "pOpcionJugador");

        pOpcionFichas.setBackground(new java.awt.Color(255, 255, 255));

        btBlancas.setBackground(new java.awt.Color(51, 51, 51));
        btBlancas.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btBlancas.setForeground(new java.awt.Color(255, 255, 255));
        btBlancas.setText("Verdes");
        btBlancas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBlancasActionPerformed(evt);
            }
        });

        btNegras.setBackground(new java.awt.Color(51, 51, 51));
        btNegras.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btNegras.setForeground(new java.awt.Color(255, 255, 255));
        btNegras.setText("Negras");
        btNegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNegrasActionPerformed(evt);
            }
        });

        btnVolverOF.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverOF.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnVolverOF.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverOF.setText("Volver");
        btnVolverOF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverOFActionPerformed(evt);
            }
        });

        lbMensaje.setFont(new java.awt.Font("Pristina", 1, 20)); // NOI18N
        lbMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMensaje.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.lightGray, new java.awt.Color(102, 102, 102)));

        javax.swing.GroupLayout pOpcionFichasLayout = new javax.swing.GroupLayout(pOpcionFichas);
        pOpcionFichas.setLayout(pOpcionFichasLayout);
        pOpcionFichasLayout.setHorizontalGroup(
            pOpcionFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOpcionFichasLayout.createSequentialGroup()
                .addGroup(pOpcionFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pOpcionFichasLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnVolverOF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pOpcionFichasLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btBlancas, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(btNegras, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOpcionFichasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        pOpcionFichasLayout.setVerticalGroup(
            pOpcionFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pOpcionFichasLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(lbMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(pOpcionFichasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBlancas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNegras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btnVolverOF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pOpciones.add(pOpcionFichas, "pOpcionFichas");
        pOpcionFichas.getAccessibleContext().setAccessibleName("");

        pUnJugador.setBackground(new java.awt.Color(255, 255, 255));

        btnFacil.setBackground(new java.awt.Color(51, 51, 51));
        btnFacil.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnFacil.setForeground(new java.awt.Color(255, 255, 255));
        btnFacil.setText("Facil");
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });

        btnNormal.setBackground(new java.awt.Color(51, 51, 51));
        btnNormal.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnNormal.setForeground(new java.awt.Color(255, 255, 255));
        btnNormal.setText("Normal");
        btnNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalActionPerformed(evt);
            }
        });

        btnDificil.setBackground(new java.awt.Color(51, 51, 51));
        btnDificil.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnDificil.setForeground(new java.awt.Color(255, 255, 255));
        btnDificil.setText("Dificil");
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });

        btnVolverUJ.setBackground(new java.awt.Color(51, 51, 51));
        btnVolverUJ.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        btnVolverUJ.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverUJ.setText("Volver");
        btnVolverUJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverUJActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUnJugadorLayout = new javax.swing.GroupLayout(pUnJugador);
        pUnJugador.setLayout(pUnJugadorLayout);
        pUnJugadorLayout.setHorizontalGroup(
            pUnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUnJugadorLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(pUnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverUJ, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        pUnJugadorLayout.setVerticalGroup(
            pUnJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUnJugadorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnVolverUJ, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pOpciones.add(pUnJugador, "pUnJugador");

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                        .addComponent(pOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InicioLayout.createSequentialGroup()
                        .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317))))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pBase.add(Inicio, "card2");

        pMolino.setBackground(new java.awt.Color(255, 255, 255));
        pMolino.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn1.setFocusable(false);
        fn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn1MouseClicked(evt);
            }
        });
        jPanel1.add(fn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 70, 70));

        fn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn2.setFocusable(false);
        fn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn2MouseClicked(evt);
            }
        });
        jPanel1.add(fn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 70, 70));

        fn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn3.setFocusable(false);
        fn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn3MouseClicked(evt);
            }
        });
        jPanel1.add(fn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 70, 70));

        fn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn4.setFocusable(false);
        fn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn4MouseClicked(evt);
            }
        });
        jPanel1.add(fn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 70, 70));

        fn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn5.setFocusable(false);
        fn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn5MouseClicked(evt);
            }
        });
        jPanel1.add(fn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 70, 70));

        fn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn6.setFocusable(false);
        fn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn6MouseClicked(evt);
            }
        });
        jPanel1.add(fn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 70, 70));

        fn7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn7.setFocusable(false);
        fn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn7MouseClicked(evt);
            }
        });
        jPanel1.add(fn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 70, 70));

        fn8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn8.setFocusable(false);
        fn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn8MouseClicked(evt);
            }
        });
        jPanel1.add(fn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 70, 70));

        fn9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fn9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaNegra.png"))); // NOI18N
        fn9.setFocusable(false);
        fn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fn9MouseClicked(evt);
            }
        });
        jPanel1.add(fn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 70, 70));

        fv9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv9.setAlignmentX(0.5F);
        fv9.setFocusable(false);
        fv9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv9MouseClicked(evt);
            }
        });
        jPanel1.add(fv9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 71, 72));

        fv8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv8.setAlignmentX(0.5F);
        fv8.setFocusable(false);
        fv8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv8MouseClicked(evt);
            }
        });
        jPanel1.add(fv8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, 71, 72));

        fv7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv7.setAlignmentX(0.5F);
        fv7.setFocusable(false);
        fv7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv7MouseClicked(evt);
            }
        });
        jPanel1.add(fv7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 71, 72));

        fv6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv6.setAlignmentX(0.5F);
        fv6.setFocusable(false);
        fv6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv6MouseClicked(evt);
            }
        });
        jPanel1.add(fv6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 71, 72));

        fv5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv5.setAlignmentX(0.5F);
        fv5.setFocusable(false);
        fv5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv5MouseClicked(evt);
            }
        });
        jPanel1.add(fv5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 310, 71, 72));

        fv4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv4.setAlignmentX(0.5F);
        fv4.setFocusable(false);
        fv4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv4MouseClicked(evt);
            }
        });
        jPanel1.add(fv4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 71, 72));

        fv3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv3.setAlignmentX(0.5F);
        fv3.setFocusable(false);
        fv3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv3MouseClicked(evt);
            }
        });
        jPanel1.add(fv3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 71, 72));

        fv2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv2.setAlignmentX(0.5F);
        fv2.setFocusable(false);
        fv2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv2MouseClicked(evt);
            }
        });
        jPanel1.add(fv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 71, 72));

        fv1.setBackground(new java.awt.Color(230, 223, 223));
        fv1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fv1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DamaBlanca.png"))); // NOI18N
        fv1.setAlignmentX(0.5F);
        fv1.setFocusable(false);
        fv1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fv1MouseClicked(evt);
            }
        });
        jPanel1.add(fv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 71, 72));

        a17.setForeground(new java.awt.Color(255, 255, 255));
        a17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a17.setFocusable(false);
        a17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a17MouseClicked(evt);
            }
        });
        jPanel1.add(a17, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 70, 70));

        a11.setForeground(new java.awt.Color(255, 255, 255));
        a11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a11.setFocusable(false);
        a11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a11MouseClicked(evt);
            }
        });
        jPanel1.add(a11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, 70));

        a22.setForeground(new java.awt.Color(255, 255, 255));
        a22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a22.setFocusable(false);
        a22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a22MouseClicked(evt);
            }
        });
        jPanel1.add(a22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 70, 70));

        a24.setForeground(new java.awt.Color(255, 255, 255));
        a24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a24.setFocusable(false);
        a24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a24MouseClicked(evt);
            }
        });
        jPanel1.add(a24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 70, 70));

        a26.setForeground(new java.awt.Color(255, 255, 255));
        a26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a26.setFocusable(false);
        a26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a26MouseClicked(evt);
            }
        });
        jPanel1.add(a26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 70, 70));

        a42.setForeground(new java.awt.Color(255, 255, 255));
        a42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a42.setFocusable(false);
        a42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a42MouseClicked(evt);
            }
        });
        jPanel1.add(a42, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 70, 70));

        a33.setForeground(new java.awt.Color(255, 255, 255));
        a33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a33.setFocusable(false);
        a33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a33MouseClicked(evt);
            }
        });
        jPanel1.add(a33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 70, 70));

        a35.setForeground(new java.awt.Color(255, 255, 255));
        a35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a35.setFocusable(false);
        a35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a35MouseClicked(evt);
            }
        });
        jPanel1.add(a35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 70, 70));

        a14.setForeground(new java.awt.Color(255, 255, 255));
        a14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a14.setFocusable(false);
        a14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a14MouseClicked(evt);
            }
        });
        jPanel1.add(a14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 70));

        a43.setForeground(new java.awt.Color(255, 255, 255));
        a43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a43.setFocusable(false);
        a43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a43MouseClicked(evt);
            }
        });
        jPanel1.add(a43, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 70, 70));

        a71.setForeground(new java.awt.Color(255, 255, 255));
        a71.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a71.setFocusable(false);
        a71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a71MouseClicked(evt);
            }
        });
        jPanel1.add(a71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 70, 70));

        a62.setForeground(new java.awt.Color(255, 255, 255));
        a62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a62.setFocusable(false);
        a62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a62MouseClicked(evt);
            }
        });
        jPanel1.add(a62, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 70, 70));

        a53.setForeground(new java.awt.Color(255, 255, 255));
        a53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a53.setFocusable(false);
        a53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a53MouseClicked(evt);
            }
        });
        jPanel1.add(a53, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 70, 70));

        a54.setForeground(new java.awt.Color(255, 255, 255));
        a54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a54.setFocusable(false);
        a54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a54MouseClicked(evt);
            }
        });
        jPanel1.add(a54, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 70, 70));

        a55.setForeground(new java.awt.Color(255, 255, 255));
        a55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a55.setFocusable(false);
        a55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a55MouseClicked(evt);
            }
        });
        jPanel1.add(a55, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 70, 70));

        a45.setForeground(new java.awt.Color(255, 255, 255));
        a45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a45.setFocusable(false);
        a45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a45MouseClicked(evt);
            }
        });
        jPanel1.add(a45, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 70, 70));

        a46.setForeground(new java.awt.Color(255, 255, 255));
        a46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a46.setFocusable(false);
        a46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a46MouseClicked(evt);
            }
        });
        jPanel1.add(a46, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 70));

        a47.setForeground(new java.awt.Color(255, 255, 255));
        a47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a47.setFocusable(false);
        a47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a47MouseClicked(evt);
            }
        });
        jPanel1.add(a47, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 70, 70));

        a66.setForeground(new java.awt.Color(255, 255, 255));
        a66.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a66.setFocusable(false);
        a66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a66MouseClicked(evt);
            }
        });
        jPanel1.add(a66, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 70, 70));

        a64.setForeground(new java.awt.Color(255, 255, 255));
        a64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a64.setFocusable(false);
        a64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a64MouseClicked(evt);
            }
        });
        jPanel1.add(a64, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 70, 70));

        a34.setForeground(new java.awt.Color(255, 255, 255));
        a34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a34.setFocusable(false);
        a34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a34MouseClicked(evt);
            }
        });
        jPanel1.add(a34, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 70, 70));

        a77.setForeground(new java.awt.Color(255, 255, 255));
        a77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a77.setFocusable(false);
        a77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a77MouseClicked(evt);
            }
        });
        jPanel1.add(a77, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 70, 70));

        a41.setForeground(new java.awt.Color(255, 255, 255));
        a41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a41.setFocusable(false);
        a41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a41MouseClicked(evt);
            }
        });
        jPanel1.add(a41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 70, 70));

        a74.setForeground(new java.awt.Color(255, 255, 255));
        a74.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a74.setFocusable(false);
        a74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a74MouseClicked(evt);
            }
        });
        jPanel1.add(a74, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 70, 70));

        lbTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/T12.png"))); // NOI18N
        lbTablero.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(lbTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 660, 580));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 620, 120));

        lbJugadorNegras.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lbJugadorNegras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lbJugadorVerde.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lbJugadorVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pMolinoLayout = new javax.swing.GroupLayout(pMolino);
        pMolino.setLayout(pMolinoLayout);
        pMolinoLayout.setHorizontalGroup(
            pMolinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMolinoLayout.createSequentialGroup()
                .addGroup(pMolinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pMolinoLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMolinoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbJugadorNegras, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbJugadorVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        pMolinoLayout.setVerticalGroup(
            pMolinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMolinoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pMolinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbJugadorVerde, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lbJugadorNegras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pBase.add(pMolino, "pMolino");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(442, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VictoriaLayout = new javax.swing.GroupLayout(Victoria);
        Victoria.setLayout(VictoriaLayout);
        VictoriaLayout.setHorizontalGroup(
            VictoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VictoriaLayout.setVerticalGroup(
            VictoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pBase.add(Victoria, "pVictoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoJuegoActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionJugador");
    }//GEN-LAST:event_btnNuevoJuegoActionPerformed


    
    private void btnUnJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnJugadorActionPerformed
        cardLayOpciones.show(pOpciones, "pUnJugador");
        numeroJugadores = 1;
        lbMensaje.setText("¿Con que color de fichas desea jugar?");
    }//GEN-LAST:event_btnUnJugadorActionPerformed

    
    
    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionFichas");
        dificultad = 1;
        
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionFichas");
        dificultad = 2;
       
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionFichas");
        dificultad = 3;//PARA LUEGO
       
    }//GEN-LAST:event_btnDificilActionPerformed

    
    
    
    
    private void btBlancasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBlancasActionPerformed
        if (numeroJugadores == 1) {
            lbJugadorVerde.setText("Jugador ");
            lbJugadorNegras.setText("Ordenador ");
            System.out.println("SOLO");
           
            t_h = 2;
            t_m = 3;

        } else {
            lbJugadorVerde.setText("Jugador 1");
            lbJugadorNegras.setText("Jugador 2");
            
            System.out.println(t);
        }
        t = 2;
        cardLayBase.show(pBase, "pMolino");
        men = new Mensaje();
        men.setLocation(this.getX()+50, this.getY()+670);
        men.setVisible(true);
        men.mens("Hola");
    }//GEN-LAST:event_btBlancasActionPerformed

    private void btNegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNegrasActionPerformed

        if (numeroJugadores == 1) {
            lbJugadorNegras.setText("Jugador ");
            lbJugadorVerde.setText("Ordenador ");
            System.out.println("SOLO");
            
            t_h = 3;
            t_m = 2;
            
        } else {
            lbJugadorNegras.setText("Jugador 1");
            lbJugadorVerde.setText("Jugador 2");
            
            System.out.println(t);
        }
        t = 3;
        cardLayBase.show(pBase, "pMolino");
        men = new Mensaje();
        men.setLocation(this.getX()+50, this.getY()+670);
        men.setVisible(true);
        men.mens("");
        
        
    }//GEN-LAST:event_btNegrasActionPerformed

    public void verVictoria(){
        switch (verficarFichaV()) {
            case 2:
                interfazVictoria("Ha ganado las blancas");
                break;
            case 3:
                interfazVictoria("Ha ganado las  negras");
                break;
            default:
                System.out.println("QUE SIGA EL JUEGO");
                break;
        }
    }
    
    public int verficarFichaV(){
        int cN=0,cB=0;
        for (int i = 0; i < 9; i++) {
            if (MaquinasBlancas[i].getX()==0&&MaquinasBlancas[i].getY()==0) {
                cB++;
            }
            if (MaquinasNegras[i].getX()==0&&MaquinasNegras[i].getY()==0) {
                cN++;
            }
        }
        
        if (cB==7) {
            return 3;
        }else if(cN==7){
            return 2;
        }
        return 0;
    }
    
    public void interfazVictoria(String men){
        trans=new Transparente();
        trans.setBounds(this.getX()+5,this.getY(),this.getWidth()-10,this.getHeight()-8);
        trans.setVisible(true);
        vict=new CuadroVictoria();
        vict.setLocation(this.getX()+200, this.getY()+250);
        vict.mensaje(men);
        vict.setVisible(true);
    }
    
    Transparente trans;
    CuadroVictoria vict;
    
    private void btnDosJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDosJugadoresActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionFichas");
        numeroJugadores = 2;
        lbMensaje.setText("¿Con que color de fichas va jugar el jugador 1?");
    }//GEN-LAST:event_btnDosJugadoresActionPerformed

    
    
    
    
    private void btVolverOJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverOJActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcion1");
    }//GEN-LAST:event_btVolverOJActionPerformed

    private void btnVolverUJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverUJActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionJugador");
    }//GEN-LAST:event_btnVolverUJActionPerformed

    private void btnVolverOFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverOFActionPerformed
        cardLayOpciones.show(pOpciones, "pOpcionJugador");
    }//GEN-LAST:event_btnVolverOFActionPerformed

    
    
    
    

    private void fn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn1MouseClicked
        jlbAux = fn1;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn1MouseClicked

    private void fn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn2MouseClicked
        jlbAux = fn2;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn2MouseClicked

    private void fn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn3MouseClicked
        jlbAux = fn3;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn3MouseClicked

    private void fn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn4MouseClicked
        jlbAux = fn4;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn4MouseClicked

    private void fn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn5MouseClicked
        jlbAux = fn5;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn5MouseClicked

    private void fn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn6MouseClicked
        jlbAux = fn6;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn6MouseClicked

    private void fn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn7MouseClicked
        jlbAux = fn7;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn7MouseClicked

    private void fn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn8MouseClicked
        jlbAux = fn8;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn8MouseClicked

    private void fn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fn9MouseClicked
        jlbAux = fn9;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_n(jlbAux);
    }//GEN-LAST:event_fn9MouseClicked

    private void fv1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv1MouseClicked
        jlbAux = fv1;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv1MouseClicked

    private void fv2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv2MouseClicked
        jlbAux = fv2;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv2MouseClicked

    private void fv3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv3MouseClicked
        jlbAux = fv3;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv3MouseClicked

    private void fv4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv4MouseClicked
        jlbAux = fv4;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv4MouseClicked

    private void fv5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv5MouseClicked
        jlbAux = fv5;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv5MouseClicked

    private void fv6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv6MouseClicked
        jlbAux = fv6;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv6MouseClicked

    private void fv7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv7MouseClicked
        jlbAux = fv7;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv7MouseClicked

    private void fv8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv8MouseClicked
        jlbAux = fv8;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv8MouseClicked

    private void fv9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fv9MouseClicked
        jlbAux = fv9;
        if (fich_Elim == 0) {
            escribir(jlbAux);
            SeleFicha(jlbAux);
        }
        eliminar_ficha_b(jlbAux);
    }//GEN-LAST:event_fv9MouseClicked

    
    
    public void eliminar_ficha_b(javax.swing.JLabel jlbAux) {
        if (fich_Elim == 1 && jlbAux.getX() != 670 && jlbAux.getX() != 760) {
            if (t == 2) {
                Tab.elim_F(Coor_y(jlbAux.getY()), Coor_x(jlbAux.getX()));
                eliminar_ficha(jlbAux);
                Fich.EliminarFicha(2);
                System.out.println("TABLERO LUEGO DE ELIMINAR: ");
                Tab.mostrarTablero();
                fich_Elim = 0;
            }
        }
    }

    public void eliminar_ficha_n(javax.swing.JLabel jlbAux) {
        if (fich_Elim == 1 && jlbAux.getX() != 670 && jlbAux.getX() != 760) {
            if (t == 3) {
                Tab.elim_F(Coor_x(jlbAux.getX()), Coor_y(jlbAux.getY()));
                eliminar_ficha(jlbAux);
                Fich.EliminarFicha(3);
                System.out.println("TABLERO LUEGO DE ELIMINAR: ");
                Tab.mostrarTablero();
                fich_Elim = 0;
            }
        }
    }

    public void SeleFicha(javax.swing.JLabel jlbAux) {
        int x, y;
        if (fase == 1) {
            x = jlbAux.getX();
            y = jlbAux.getY();
            Coor(x, y);
            veri = Tab.posiValido(COORx, COORy, t);//si v es 0 se escogió una posición correcta
        }
    }

    
    
    
    //TABLERO
    private void a11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a11MouseClicked
        xt = 0;
        yt = 0;
        mover(jlbAux, a11);
        escribir(a11);
        verVictoria();
    }//GEN-LAST:event_a11MouseClicked

    private void a14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a14MouseClicked
        xt = 0;
        yt = 3;
        mover(jlbAux, a14);
        escribir(a14);
        verVictoria();
    }//GEN-LAST:event_a14MouseClicked

    private void a17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a17MouseClicked
        xt = 0;
        yt = 6;
        mover(jlbAux, a17);
        escribir(a17);
        verVictoria();
    }//GEN-LAST:event_a17MouseClicked

    private void a22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a22MouseClicked
        xt = 1;
        yt = 1;
        mover(jlbAux, a22);
        escribir(a22);
        verVictoria();
    }//GEN-LAST:event_a22MouseClicked

    private void a24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a24MouseClicked
        xt = 1;
        yt = 3;
        mover(jlbAux, a24);
        escribir(a24);
        verVictoria();
    }//GEN-LAST:event_a24MouseClicked

    private void a26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a26MouseClicked
        xt = 1;
        yt = 5;
        mover(jlbAux, a26);
        escribir(a26);
        verVictoria();
    }//GEN-LAST:event_a26MouseClicked

    private void a33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a33MouseClicked
        xt = 2;
        yt = 2;
        mover(jlbAux, a33);
        escribir(a33);
        verVictoria();
    }//GEN-LAST:event_a33MouseClicked

    private void a34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a34MouseClicked
        xt = 2;
        yt = 3;
        mover(jlbAux, a34);
        escribir(a34);
        verVictoria();
    }//GEN-LAST:event_a34MouseClicked

    private void a35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a35MouseClicked
        xt = 2;
        yt = 4;
        mover(jlbAux, a35);
        escribir(a35);
        verVictoria();
    }//GEN-LAST:event_a35MouseClicked

    private void a41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a41MouseClicked
        xt = 3;
        yt = 0;
        mover(jlbAux, a41);
        escribir(a41);
        verVictoria();
    }//GEN-LAST:event_a41MouseClicked

    private void a42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a42MouseClicked
        xt = 3;
        yt = 1;
        mover(jlbAux, a42);
        escribir(a42);
        verVictoria();
    }//GEN-LAST:event_a42MouseClicked

    private void a43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a43MouseClicked
        xt = 3;
        yt = 2;
        mover(jlbAux, a43);
        escribir(a43);
        verVictoria();
    }//GEN-LAST:event_a43MouseClicked

    private void a45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a45MouseClicked
        xt = 3;
        yt = 4;
        mover(jlbAux, a45);
        escribir(a45);
        verVictoria();
    }//GEN-LAST:event_a45MouseClicked

    private void a46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a46MouseClicked
        xt = 3;
        yt = 5;
        mover(jlbAux, a46);
        escribir(a46);
        verVictoria();
    }//GEN-LAST:event_a46MouseClicked

    private void a47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a47MouseClicked
        xt = 3;
        yt = 6;
        mover(jlbAux, a47);
        escribir(a47);
        verVictoria();
    }//GEN-LAST:event_a47MouseClicked

    private void a53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a53MouseClicked
        xt = 4;
        yt = 2;
        mover(jlbAux, a53);
        escribir(a53);
        verVictoria();
    }//GEN-LAST:event_a53MouseClicked

    private void a54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a54MouseClicked
        xt = 4;
        yt = 3;
        mover(jlbAux, a54);
        escribir(a54);
        verVictoria();
    }//GEN-LAST:event_a54MouseClicked

    private void a55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a55MouseClicked
        xt = 4;
        yt = 4;
        mover(jlbAux, a55);
        escribir(a55);
        verVictoria();
    }//GEN-LAST:event_a55MouseClicked

    private void a62MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a62MouseClicked
        xt = 5;
        yt = 1;
        mover(jlbAux, a62);
        escribir(a62);
        verVictoria();
    }//GEN-LAST:event_a62MouseClicked

    private void a64MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a64MouseClicked
        xt = 5;
        yt = 3;
        mover(jlbAux, a64);
        escribir(a64);
        verVictoria();
    }//GEN-LAST:event_a64MouseClicked

    private void a66MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a66MouseClicked
        xt = 5;
        yt = 5;
        mover(jlbAux, a66);
        escribir(a66);
        verVictoria();
    }//GEN-LAST:event_a66MouseClicked

    private void a71MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a71MouseClicked
        xt = 6;
        yt = 0;
        mover(jlbAux, a71);
        escribir(a71);
        verVictoria();
    }//GEN-LAST:event_a71MouseClicked

    private void a74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a74MouseClicked
        xt = 6;
        yt = 3;
        mover(jlbAux, a74);
        escribir(a74);
        verVictoria();
    }//GEN-LAST:event_a74MouseClicked

    private void a77MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a77MouseClicked
        xt = 6;
        yt = 6;
        mover(jlbAux, a77);
        escribir(a77);
        verVictoria();
    }//GEN-LAST:event_a77MouseClicked

    private void btnVerReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReglasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerReglasActionPerformed
    
    
    
    
    //FUNCION RAIZ
    
    public void mover(JLabel jlbOrigen,JLabel jlbMeta) {
        if (numeroJugadores == 2) {
            Juego_2(jlbOrigen, jlbMeta);
        }
        if (numeroJugadores == 1) {
            if (t_h == 3) {
                Juego_1_n(jlbOrigen, jlbMeta);
            }

        }
    }
    
    
    //JUGAR LAS NEGRAS HUMANO-MAQUINA
    public void Juego_1_n(JLabel jlbOrigen, JLabel jlbMeta) {
        int xo, yo, xm, ym;
        if (fase == 0) {
            
            if (t == 3) {
                men.mens("Fase 1 | Juega con las fichas negras");
                xo = jlbOrigen.getX();
                yo = jlbOrigen.getY();
                xm = jlbMeta.getX();
                ym = jlbMeta.getY();
                jueganNegras(xo, jlbOrigen, jlbMeta);
            }
            if (fich_Elim == 0) {
                Tab.mostrarTablero();
                //esperar();
                colocarMaquinaBlancas();

            }
            fase = Fich.CambioFase();
            if (fase == 1) {
                System.out.println("Se acabó la primera fase");
                men.mens("Fase 2 | Juega con las fichas negras");
            }
        }
        if (fase == 1) {
            System.out.println("LLEGA A 2DA FASE");
            //jLabelFase.setText("Segunda fase");
            if (t == 3) {
                System.out.println("TURNO DEL HUMANO");
                xo = jlbOrigen.getX();
                yo = jlbOrigen.getY();
                xm = jlbMeta.getX();
                ym = jlbMeta.getY();
                fase3(xo, yo, xm, ym, jlbOrigen, jlbMeta);
            }
            if (fich_Elim == 0) {
                //esperar();
                MoverMaquinaBlanca();
            }
        }

    }

    
    
    //JUGAR LAS NEGRAS O BLANCAS  HUMANO-HUMANO
    public void Juego_2(JLabel jlbOrigen, JLabel jlbMeta) {
        int xo, yo, xm, ym;
        if (fase == 0) {

            xo = jlbOrigen.getX();
            yo = jlbOrigen.getY();
            xm = jlbMeta.getX();
            ym = jlbMeta.getY();
            if (t == 2) {
                jueganBlancas(xo, jlbOrigen, jlbMeta);
            }
            if (t == 3) {
                jueganNegras(xo, jlbOrigen, jlbMeta);
            }
            fase = Fich.CambioFase();
            if (fase == 1) {
                System.out.println("Se acabó la primera fase");
                men.mens("Fase 1 completada");
            }
            //jLabelFase.setText(null);
        }
        if (fase == 1) {
            xo = jlbOrigen.getX();
            yo = jlbOrigen.getY();
            xm = jlbMeta.getX();
            ym = jlbMeta.getY();

            if (t == 2) {
                fase2(xo, yo, xm, ym, jlbOrigen, jlbMeta);
                Tab.mostrarTablero();
            }
            if (t == 3) {
                fase3(xo, yo, xm, ym, jlbOrigen, jlbMeta);
                Tab.mostrarTablero();
            }

        }
    }

    
    
    
    //SE UTLIZAN PARA LAS 2 FASES
    
    private void jueganBlancas(int xo,JLabel jlbOrigen, JLabel jlbMeta) {
        if (xo == 760) {
            mover1(jlbOrigen, jlbMeta);
            Fich.FichaColocada(1, t);//FICHA DESCONTADA DEL VECTOR
            int Fc = Tab.ColocarFicha(xt, yt, t);//FICHA COLOCADA EN EL TABLERO
            if (Tab.comerF(t) == 1) {
                fich_Elim = 1;
                System.out.println("COMEEE LAS BLANCAS (FASE 1)");
            }

            t = 3;
            men.mens("Fase1 | Juega con las fichas negras");
            System.out.println("Juegan las negras");
        } else {
            //No se ha escogido una posición blanca por lo que se debe decir que escoga una de ellas
            //System.out.println("Escoge una blanca");
        }
    }

    private void jueganNegras(int xo,JLabel jlbOrigen, JLabel jlbMeta) {
        if (xo == 670) {

            System.out.println("");
            mover1(jlbOrigen, jlbMeta);
            Fich.FichaColocada(1, t);
            int Fc = Tab.ColocarFicha(xt, yt, t);
            if (Tab.comerF(t) == 1) {
                fich_Elim = 1;
                System.out.println("COMEE LAS NEGRAS (FASE 1)");
            }
            t = 2;
            men.mens("Fase1 | Juega con las fichas blancas");
            System.out.println("Juegan las blancas.");
        } else {
            //No se ha escogido una posición blanca por lo que se debe decir que escoga una de ellas
            //System.out.println("Escoge una negra");
        }
    }

    
    
    
    //FICHAS BLANCAS-MAQUINA
    
        //FASE 1
    public void colocarMaquinaBlancas() {
        if (t == 2) {
            if (dificultad == 1) {
                //maquina blancas 2
                int xa, ya;
                fichasEliminadas = Tab.f;
                Estado inicial = new Estado(Tab.tablero, 3, fichas, fichasEliminadas);
                SistemaProduccion sp = new SistemaProduccion(inicial, 1);
                xa = sp.geteFinal().getEstado().getJugada().getXm();
                ya = sp.geteFinal().getEstado().getJugada().getYm();
                Tab.ColocarFicha(xa, ya, 2);
                Fich.FichaColocada(1, 2);
                mover1(MaquinasBlancas[conMaquinas], retornarUbicacionT(xa, ya));
                conMaquinas++;
                EliminarMaquinaBlanca();
                t = 3;
                System.out.println("TABLERO DEL MAIN: ");
                Tab.mostrarTablero();
            }
            if (dificultad == 2) {
                //Modo normal
                int xa, ya;
                fichasEliminadas = Tab.f;
                Estado inicial = new Estado(Tab.tablero, 3, fichas, fichasEliminadas);
                SistemaProduccion sp = new SistemaProduccion(1, inicial, 1);
                xa = sp.geteFinal().getEstado().getJugada().getXm();
                ya = sp.geteFinal().getEstado().getJugada().getYm();
                Tab.ColocarFicha(xa, ya, 2);
                Fich.FichaColocada(1, 2);
                mover1(MaquinasBlancas[conMaquinas], retornarUbicacionT(xa, ya));
                conMaquinas++;
                EliminarMaquinaBlanca();
                t = 3;
                System.out.println("TABLERO DEL MAIN: ");
                Tab.mostrarTablero();
            }
            if (dificultad == 3) {
                //Modo experto
                int xa, ya;
                fichasEliminadas = Tab.f;
                Estado inicial = new Estado(Tab.tablero, 3, fichas, fichasEliminadas);
                SistemaProduccion sp = new SistemaProduccion(2, inicial, 1);
                xa = sp.geteFinal().getEstado().getJugada().getXm();
                ya = sp.geteFinal().getEstado().getJugada().getYm();
                /*
                System.out.println("EL VALOR DE X ESCOGIDO POR LA MAQUINA ES: " + xa);
                System.out.println("EL VALOR DE Y ESCOGIDO POR LA MAQUINA ES: " + ya);
                */
                Tab.ColocarFicha(xa, ya, 2);
                Fich.FichaColocada(1, 2);
                mover1(MaquinasBlancas[conMaquinas], retornarUbicacionT(xa, ya));
                conMaquinas++;
                EliminarMaquinaBlanca();
                t = 3;
                System.out.println("TABLERO DEL MAIN: ");
                Tab.mostrarTablero();
            }
        }
        
    }
        //FASE 2
    public void MoverMaquinaBlanca() {
        if (t == 2) {
            if (dificultad == 1) {
                int xa, ya, xb, yb;
                fichasEliminadas = Tab.f;
                Estado inicial = new Estado(Tab.tablero, 3, fichas, fichasEliminadas);
                SistemaProduccion sp = new SistemaProduccion(inicial, 2);
                xa = sp.geteFinal().getEstado().getJugada().getXo();
                ya = sp.geteFinal().getEstado().getJugada().getYo();
                xb = sp.geteFinal().getEstado().getJugada().getXm();
                yb = sp.geteFinal().getEstado().getJugada().getYm();
                /*
                System.out.println("EL VALOR DE X1 ESCOGIDO POR LA MAQUINA ES: " + xa);
                System.out.println("EL VALOR DE Y1 ESCOGIDO POR LA MAQUINA ES: " + ya);
                System.out.println("EL VALOR DE X2 ESCOGIDO POR LA MAQUINA ES: " + xb);
                System.out.println("EL VALOR DE Y2 ESCOGIDO POR LA MAQUINA ES: " + yb);
                */
                Tab.moverA(xa, ya, xb, yb, 2);
                jugada.setXo(xa);
                jugada.setYo(ya);
                mover1(retornarFicha(ya, xa), retornarUbicacionT(xb, yb));
                EliminarMaquinaBlanca();
                t = 3;
                System.out.println("TABLERO DEL MAIN: ");
                Tab.mostrarTablero();
            }
            if (dificultad == 2) {
                //Modo normal
                int xa, ya, xb, yb;
                fichasEliminadas = Tab.f;
                Estado inicial = new Estado(Tab.tablero, 3, fichas, fichasEliminadas);
                SistemaProduccion sp = new SistemaProduccion(1, inicial, 2);
                xa = sp.geteFinal().getEstado().getJugada().getXo();
                ya = sp.geteFinal().getEstado().getJugada().getYo();
                xb = sp.geteFinal().getEstado().getJugada().getXm();
                yb = sp.geteFinal().getEstado().getJugada().getYm();
                /*
                System.out.println("EL VALOR DE X1 ESCOGIDO POR LA MAQUINA ES: " + xa);
                System.out.println("EL VALOR DE Y1 ESCOGIDO POR LA MAQUINA ES: " + ya);
                System.out.println("EL VALOR DE X2 ESCOGIDO POR LA MAQUINA ES: " + xb);
                System.out.println("EL VALOR DE Y2 ESCOGIDO POR LA MAQUINA ES: " + yb);
                */
                Tab.moverA(xa, ya, xb, yb, 2);
                jugada.setXo(xa);
                jugada.setYo(ya);
                mover1(retornarFicha(ya, xa), retornarUbicacionT(xb, yb));
                EliminarMaquinaBlanca();
                t = 3;
                System.out.println("TABLERO DEL MAIN: ");
                Tab.mostrarTablero();
            }
            if (dificultad == 3) {
                //Modo experto
                int xa, ya, xb, yb;
                fichasEliminadas = Tab.f;
                Estado inicial = new Estado(Tab.tablero, 3, fichas, fichasEliminadas);
                SistemaProduccion sp = new SistemaProduccion(1, inicial, 2);
                xa = sp.geteFinal().getEstado().getJugada().getXo();
                ya = sp.geteFinal().getEstado().getJugada().getYo();
                xb = sp.geteFinal().getEstado().getJugada().getXm();
                yb = sp.geteFinal().getEstado().getJugada().getYm();
                /*
                System.out.println("EL VALOR DE X1 ESCOGIDO POR LA MAQUINA ES: " + xa);
                System.out.println("EL VALOR DE Y1 ESCOGIDO POR LA MAQUINA ES: " + ya);
                System.out.println("EL VALOR DE X2 ESCOGIDO POR LA MAQUINA ES: " + xb);
                System.out.println("EL VALOR DE Y2 ESCOGIDO POR LA MAQUINA ES: " + yb);
                */
                Tab.moverA(xa, ya, xb, yb, 2);
                jugada.setXo(xa);
                jugada.setYo(ya);
                mover1(retornarFicha(ya, xa), retornarUbicacionT(xb, yb));
                EliminarMaquinaBlanca();

                System.out.println("TABLERO DEL MAIN: ");
                if (Fich.Victoria(t) == 1) {
                    men.mens("Victoria de la maquina");
                }
                t = 3;
                Tab.mostrarTablero();
            }

        }
        
    }
        //AMBAS FASES
    public void EliminarMaquinaBlanca() {
        if (Tab.comerF(t) == 1) {
            int a1, b1;
            fich_Elim = 1;
            System.out.println("COMEE LAS NEGRAS (FASE 1)");
            if (t == 2) {
                int a;
                do {
                    a = (int) (Math.random() * 9);
                } while (MaquinasNegras[a].getX() == 0 || MaquinasNegras[a].getX() == 670);
                //esperar();
                System.out.println("A" + a);
                System.out.println("X1: " + MaquinasNegras[a].getX());
                System.out.println("Y1: " + MaquinasNegras[a].getY());
                a1 = Coor_x(MaquinasNegras[a].getX());
                b1 = Coor_y(MaquinasNegras[a].getY());
                System.out.println("A1: " + a1);
                System.out.println("B1: " + b1);
                Tab.elim_F(b1, a1);
                eliminar_ficha(MaquinasNegras[a]);
                Fich.EliminarFicha(t_h);
                fich_Elim = 0;
            }
        }
    }
    
    
    
    //FICHAS NEGRAS-MAQUINA
    
    

   
    
    //FASE 2 SOLO UTILIZA EL HUMANO-SOLO MOVER
    
    //FICHAS BLANCAS SEGUNDA FASE
    public void fase2(int xo, int yo, int xm, int ym, JLabel jlbOrigen, JLabel jlbMeta) {
        int a;
        if (veri == 0) {
            Coor1(xm, ym);
            a = Tab.moverA(COORx, COORy, x1, y1, t);
            if (a == 1) {
                mover1(jlbOrigen, jlbMeta);

                if (Tab.comerF(t) == 1) {
                    fich_Elim = 1;
                    System.out.println("COME UNA FICHA CONTRARIA: ");
                }
                if (Fich.Victoria(t) == 1) {
                    System.out.println("Ganan las blancas");
                    men.mens("Victoria");
                } else {
                    System.out.println("Juegan las negras ");
                }
                t = 3;
                men.mens("Fase 2 | Juega con las fichas negras");
            }
            veri = 1;
        } else {
            //System.out.println("escoge una ficha tuya");
        }

    }

    //FICHAS NEGRAS SEGUNDA FASE
    public void fase3(int xo, int yo, int xm, int ym, JLabel jlbOrigen, JLabel jlbMeta) {
        int a;

        Coor1(xm, ym);
        a = Tab.moverA(COORy, COORx, y1, x1, t);
        System.out.println("A HUMANO: " + a);
        if (a == 1) {
            mover1(jlbOrigen, jlbMeta);

            if (Tab.comerF(t) == 1) {
                fich_Elim = 1;
                System.out.println("COME UNA FICHA CONTRARIA: ");
            }
            if (Fich.Victoria(t) == 2) {
                System.out.println("Ganan las negras");

            } else {
                System.out.println("Juegan las blancas");
            }
            t = 2;
            men.mens("Fase 2 | Juega con las fichas blancas");
        }
        veri = 1;

    }

    
    
    
    
    //__________________________________________________________________________
    
    
    
    //FUNCIONES DE APOYO
    
    public void escribir(javax.swing.JLabel jlbOrigen) {
        int xo, yo;

        xo = jlbOrigen.getX();
        yo = jlbOrigen.getY();
        System.out.println("(x,y)=" + xo + ", " + yo);
    }

    public void cambio() {
        if (t == 2) {
            t = 3;
        } else {
            t = 2;
        }
    }

    public void Coor(int a, int b) {
        COORx = Coor_x(a);
        COORy = Coor_y(b);
    }

    public void Coor1(int a, int b) {
        x1 = Coor_x(a);
        y1 = Coor_y(b);
    }

    public int Coor_x(int a) {
        int x = 0;
        switch (a) {
            case 60:
                x = 0;
                break;
            case 140:
                x = 1;
                break;
            case 200:
                x = 2;
                break;
            case 300:
                x = 3;
                break;
            case 390:
                x = 4;
                break;
            case 460:
                x = 5;
                break;
            case 530:
                x = 6;
                break;
        }

        return x;
    }

    public int Coor_y(int a) {
        int y = 0;
        switch (a) {
            case 60:
                y = 0;
                break;
            case 120:
                y = 1;
                break;
            case 190:
                y = 2;
                break;
            case 260:
                y = 3;
                break;
            case 330:
                y = 4;
                break;
            case 400:
                y = 5;
                break;
            case 470:
                y = 6;
                break;
        }
        return y;
    }

    public int Coor_y1(int a) {
        int y = 0;
        switch (a) {
            case 0:
                y = 60;
                break;
            case 1:
                y = 120;
                break;
            case 2:
                y = 190;
                break;
            case 3:
                y = 260;
                break;
            case 4:
                y = 330;
                break;
            case 5:
                y = 400;
                break;
            case 6:
                y = 470;
                break;
        }
        return y;
    }

    public int Coor_x1(int a) {
        int x = 0;
        switch (a) {
            case 0:
                x = 60;
                break;
            case 1:
                x = 140;
                break;
            case 2:
                x = 200;
                break;
            case 3:
                x = 300;
                break;
            case 4:
                x = 390;
                break;
            case 5:
                x = 460;
                break;
            case 6:
                x = 530;
                break;
        }
        return x;
    }
  
    private void asignarBlancas() {
        MaquinasBlancas[0] = fv1;
        MaquinasBlancas[1] = fv2;
        MaquinasBlancas[2] = fv3;
        MaquinasBlancas[3] = fv4;
        MaquinasBlancas[4] = fv5;
        MaquinasBlancas[5] = fv6;
        MaquinasBlancas[6] = fv7;
        MaquinasBlancas[7] = fv8;
        MaquinasBlancas[8] = fv9;

    }

    private void asignarNegras() {
        MaquinasNegras[0] = fn1;
        MaquinasNegras[1] = fn2;
        MaquinasNegras[2] = fn3;
        MaquinasNegras[3] = fn4;
        MaquinasNegras[4] = fn5;
        MaquinasNegras[5] = fn6;
        MaquinasNegras[6] = fn7;
        MaquinasNegras[7] = fn8;
        MaquinasNegras[8] = fn9;

    }

    public JLabel retornarFicha(int x, int y) {
        int x1, y1;
        x1 = Coor_x1(x);
        y1 = Coor_y1(y);
        for (int i = 0; i < 9; i++) {
            if (MaquinasBlancas[i].getX() == x1 && MaquinasBlancas[i].getY() == y1) {
                return MaquinasBlancas[i];
            }
        }
        return null;
    }

    public JLabel retornarUbicacionT(int x, int y) {
        if (x == 0 && y == 0) {
            return a11;
        }
        if (x == 0 && y == 3) {
            return a14;
        }
        if (x == 0 && y == 6) {
            return a17;
        }
        if (x == 1 && y == 1) {
            return a22;
        }
        if (x == 1 && y == 3) {
            return a24;
        }
        if (x == 1 && y == 5) {
            return a26;
        }
        if (x == 2 && y == 2) {
            return a33;
        }
        if (x == 2 && y == 3) {
            return a34;
        }
        if (x == 2 && y == 4) {
            return a35;
        }
        if (x == 3 && y == 0) {
            return a41;
        }
        if (x == 3 && y == 1) {
            return a42;
        }
        if (x == 3 && y == 2) {
            return a43;
        }
        if (x == 3 && y == 4) {
            return a45;
        }
        if (x == 3 && y == 5) {
            return a46;
        }
        if (x == 3 && y == 6) {
            return a47;
        }
        if (x == 4 && y == 2) {
            return a53;
        }
        if (x == 4 && y == 3) {
            return a54;
        }
        if (x == 4 && y == 4) {
            return a55;
        }
        if (x == 5 && y == 1) {
            return a62;
        }
        if (x == 5 && y == 3) {
            return a64;
        }
        if (x == 5 && y == 5) {
            return a66;
        }
        if (x == 6 && y == 0) {
            return a71;
        }
        if (x == 6 && y == 3) {
            return a74;
        }
        if (x == 6 && y == 6) {
            return a77;
        } else {
            System.out.println("Error de ubicacion de tablero " + x + "," + y);
            return null;
        }
    }
/*
    public void esperar() {
        try {
            System.out.println("esperando...");
            Thread.sleep(100);
            System.out.println("Termino la espera");

        } catch (InterruptedException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     */
    public void mover1(javax.swing.JLabel jlbOrigen, javax.swing.JLabel jlbMeta) {
        MyActionListener mov = new MyActionListener(jlbOrigen, jlbMeta);
        Timer timer = new Timer(1, mov);
        mov.timer = timer;
        timer.start();
    }
    
    public void eliminar_ficha(javax.swing.JLabel ficha) {
        ficha.setLocation(0, 0);
        ficha.setSize(0, 0);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Victoria;
    private javax.swing.JLabel a11;
    private javax.swing.JLabel a14;
    private javax.swing.JLabel a17;
    private javax.swing.JLabel a22;
    private javax.swing.JLabel a24;
    private javax.swing.JLabel a26;
    private javax.swing.JLabel a33;
    private javax.swing.JLabel a34;
    private javax.swing.JLabel a35;
    private javax.swing.JLabel a41;
    private javax.swing.JLabel a42;
    private javax.swing.JLabel a43;
    private javax.swing.JLabel a45;
    private javax.swing.JLabel a46;
    private javax.swing.JLabel a47;
    private javax.swing.JLabel a53;
    private javax.swing.JLabel a54;
    private javax.swing.JLabel a55;
    private javax.swing.JLabel a62;
    private javax.swing.JLabel a64;
    private javax.swing.JLabel a66;
    private javax.swing.JLabel a71;
    private javax.swing.JLabel a74;
    private javax.swing.JLabel a77;
    private javax.swing.JButton btBlancas;
    private javax.swing.JButton btNegras;
    private javax.swing.JButton btVolverOJ;
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnDosJugadores;
    private javax.swing.JButton btnFacil;
    private javax.swing.JButton btnNormal;
    private javax.swing.JButton btnNuevoJuego;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnUnJugador;
    private javax.swing.JButton btnVerReglas;
    private javax.swing.JButton btnVolverOF;
    private javax.swing.JButton btnVolverUJ;
    private javax.swing.JLabel fn1;
    private javax.swing.JLabel fn2;
    private javax.swing.JLabel fn3;
    private javax.swing.JLabel fn4;
    private javax.swing.JLabel fn5;
    private javax.swing.JLabel fn6;
    private javax.swing.JLabel fn7;
    private javax.swing.JLabel fn8;
    private javax.swing.JLabel fn9;
    private javax.swing.JLabel fv1;
    private javax.swing.JLabel fv2;
    private javax.swing.JLabel fv3;
    private javax.swing.JLabel fv4;
    private javax.swing.JLabel fv5;
    private javax.swing.JLabel fv6;
    private javax.swing.JLabel fv7;
    private javax.swing.JLabel fv8;
    private javax.swing.JLabel fv9;
    private javax.swing.JPanel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbJugadorNegras;
    private javax.swing.JLabel lbJugadorVerde;
    private javax.swing.JLabel lbMensaje;
    private javax.swing.JLabel lbTablero;
    private javax.swing.JPanel pBase;
    private javax.swing.JPanel pMolino;
    private javax.swing.JPanel pOpcion1;
    private javax.swing.JPanel pOpcionFichas;
    private javax.swing.JPanel pOpcionJugador;
    private javax.swing.JPanel pOpciones;
    private javax.swing.JPanel pUnJugador;
    // End of variables declaration//GEN-END:variables
}
